### ISSUE TITLE
Editor injects spaces after every second letter press in safari in some conditions

### ISSUE THREAD

**Issue by ZacSweers** [romannurik/SlidesCodeHighlighter#72]
Not really sure what's going on but easy to reproduce. Only seems to happen in safari

https://user-images.githubusercontent.com/1361086/229913424-1460698b-3b7a-4507-9c37-4fa2aa6db214.mov

**Comment by romannurik** [comment]
Hm very odd. I'll need to see if there's a new version of Monaco to update to to fix this?

**Comment by romannurik** [comment]
Finally got around to trying this out, and nope — still occurs in the latest versions of Monaco Editor on Safari ... not sure what could be causing it -_-

**Comment by louis993546** [comment]
ok did some debugging and I feel like it might be a WebKit thing:

e.g.
In here, I just pressed the `f` key after `a`

![Screenshot 2023-11-10 at 16 29 43](https://github.com/romannurik/SlidesCodeHighlighter/assets/3873011/4594710f-9441-4881-a66a-cbe03abe6281)

and you can see that in the debugger for some reason, `textArea.getValue()` returns
```
fun something() {
        af }
```

instead of 
```
fun something() {
        af
}
```
([`textArea` is just a wrapper on the HTML element `<textarea>`](https://github.com/microsoft/vscode/blob/119ea923e537b24565df8b1cdc21951fd45a3989/src/vs/editor/browser/controller/textAreaInput.ts#L716))

Which leads to 1 weird way to workaround it: just make sure you are typing on the last line in Safari, and then there is no more `\n` for WebKit to mix up 😂 . 


https://github.com/romannurik/SlidesCodeHighlighter/assets/3873011/5d38bd8b-5479-4389-a736-e40da80cb058

**Comment by romannurik** [comment]
I just updated to the latest `monaco-editor`, would love if someone wants to see if this is still an issue :-/

**Comment by louis993546** [comment]
@romannurik seems the same unfortunately

**Comment by romannurik** [comment]
Gahhh.. another option is to just switch to CodeMirror. I may try that at some point soon.

**Comment by romannurik** [comment]
Found the issue, it was with a quirk specific to SlidesCodeHighlighter and CSS styling.... lol. Fixed.
